version: "3.1"
networks:
    api:
        driver: bridge
volumes:
    database:
        driver: local
services:
    api_php:
        image: projeto19
        container_name: api_php
        restart: unless-stopped
        tty: true
        working_dir: /application
        volumes:
          - ./src:/application
        ports:
            - "8080:80"
        links:
            - mysql  
        networks:
          - api
    mysql:
        image: mysql:5.7
        container_name: db-mysql
        restart: always
        ports:
            - "33061:3306"
        command: --init-file /data/application/init.sql
        volumes:
            - ./docker/init.sql:/data/application/init.sql
            - database:/var/lib/mysql/
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: supersenha
            MYSQL_DATABASE: mydb
            MYSQL_USER: mysql
            MYSQL_PASSWORD: supersenha
        networks:
          - api