version: "3.1"
networks:
    api:
        driver: bridge
volumes:
    database:
        driver: local
services:
    nginx:
        image: nginx:alpine
        container_name: api-nginx
        restart: unless-stopped
        tty: true
        working_dir: /application
        volumes:
            - ./src:/application
            - ./docker/nginx.conf:/etc/nginx/conf.d
        ports:
            - "8080:80"
        links:
            - mysql            
        networks:
            - api
    webserver:
        image: diforg/ws-php8.1:1.0.4
        container_name: ws-php8.1
        restart: unless-stopped
        tty: true
        working_dir: /application
        volumes:
          - ./src:/application
        networks:
          - api
    mysql:
        image: mysql:5.7
        container_name: db-mysql
        restart: always
        ports:
            - "33061:3306"
        command: --init-file /data/application/init.sql
        volumes:
            - ./docker/init.sql:/data/application/init.sql
            - database:/var/lib/mysql/
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: supersenha
            MYSQL_DATABASE: mydb
            MYSQL_USER: mysql
            MYSQL_PASSWORD: supersenha
        networks:
          - api